# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 14:13
from __future__ import unicode_literals

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
    ]
