# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180213_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='person',
            name='partial_date',
            field=models.CharField(blank=True, choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
