# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180227_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_monthday',
            field=models.PositiveIntegerField(blank=True, help_text='Use format DD', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
