# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polynym',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
