# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0003_auto_20180213_0941'),
        ('person_name', '0002_polynym_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mononym',
            name='poet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poet.Poet'),
        ),
        migrations.AddField(
            model_name='pictonym',
            name='poet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poet.Poet'),
        ),
        migrations.AddField(
            model_name='polynym',
            name='poet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poet.Poet'),
        ),
    ]
