# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('person_name', '0003_auto_20180213_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mononym',
            name='poet',
        ),
        migrations.RemoveField(
            model_name='pictonym',
            name='poet',
        ),
        migrations.RemoveField(
            model_name='polynym',
            name='poet',
        ),
        migrations.AddField(
            model_name='mononym',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
        migrations.AddField(
            model_name='pictonym',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
        migrations.AddField(
            model_name='polynym',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
    ]
