# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mononyms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_name.Mononym')),
                ('pictonyms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_name.Pictonym')),
                ('polynyms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_name.Polynym')),
            ],
        ),
    ]
