# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='mononyms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_name.Mononym'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='pictonyms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_name.Pictonym'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='polynyms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_name.Polynym'),
        ),
    ]
