# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0002_auto_20180213_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poet',
            name='mononyms',
        ),
        migrations.RemoveField(
            model_name='poet',
            name='pictonyms',
        ),
        migrations.RemoveField(
            model_name='poet',
            name='polynyms',
        ),
        migrations.AddField(
            model_name='poet',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
